#!/bin/bash
# With -b option you can force a rebuild of the docker image.
# This option is not activated by default to save time.

cd "$( dirname "$( readlink -f "$0" )" )"
ikey="bastis-cmd-ide"

# Check for lock file first.
[ -f CMDIDE_RUNNING ] && { echo "cmdide is running."; exit 0; }
touch CMDIDE_RUNNING

# Always build container first
if [ "$1" == "-b" ]
then
    git submodule update --remote
    # docker rmi -f bastis-cmd-ide 2> /dev/null
    docker build -t $ikey .
    [ $? != 0 ] && {
        echo "Build-step failed. Will abort."
        rm -f CMDIDE_RUNNING
        exit 1
    }
fi

if [ -z $( docker images -q $ikey | head -n1 ) ]
then
    echo "-- image has not been created yet. run with -b option."
    rm -f CMDIDE_RUNNING
    exit 1
fi

# check if there is a container from that image
container_id=$( docker ps -a --filter "ancestor=${ikey}:latest" -q | head -n1 )

if [ ! -z $container_id ]
then
    echo "-- restarting container $container_id"
    clear
    docker start -i $container_id
else
    echo "-- creating new container"
    clear
    docker run \
        `# Run as interactive session`\
        -ti \
        `# Use host network`\
        --net=host \
        `# Reference image`\
        $ikey
fi

# remove lock file
rm -f CMDIDE_RUNNING
